# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('birthday', models.DateField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
